// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaCaixaPostalIA.Data;

#nullable disable

namespace SistemaCaixaPostalIA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220164021_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.CaixaPostal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Codigo");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("CpfCnpj");

                    b.Property<DateTime>("DataAluguel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("DataAluguel")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("DiaVencimento");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("IdCliente");

                    b.Property<short>("IdSocio")
                        .HasColumnType("smallint")
                        .HasColumnName("IdSocio");

                    b.Property<int>("IdStatusCaixa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("IdStatusCaixa");

                    b.Property<string>("NomeEmpresa")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("NomeEmpresa");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorMensal");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdSocio");

                    b.HasIndex("IdStatusCaixa");

                    b.ToTable("CaixasPostais", null, t =>
                        {
                            t.HasCheckConstraint("CK_CaixasPostais_DiaVencimento", "\"DiaVencimento\" BETWEEN 1 AND 31");
                        });
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.CaixaStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("CaixasStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ativa"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Bloqueada"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Cancelada"
                        });
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("Email");

                    b.Property<int>("IdClienteStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("IdClienteStatus");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("Telefone");

                    b.HasKey("Id");

                    b.HasIndex("IdClienteStatus");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.ClienteStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("ClientesStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ativo"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Inativo"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Inadimplente"
                        });
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.Cobranca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataLiquidacao")
                        .HasColumnType("date")
                        .HasColumnName("DataLiquidacao");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("DataVencimento");

                    b.Property<int>("IdCaixaPostal")
                        .HasColumnType("integer")
                        .HasColumnName("IdCaixaPostal");

                    b.Property<short>("IdStatusCobranca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("IdStatusCobranca");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("IdCaixaPostal");

                    b.HasIndex("IdStatusCobranca");

                    b.ToTable("Cobrancas", (string)null);
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.CobrancaStatus", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("CobrancasStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Nome = "Pendente"
                        },
                        new
                        {
                            Id = (short)2,
                            Nome = "Pago"
                        },
                        new
                        {
                            Id = (short)3,
                            Nome = "Atrasado"
                        },
                        new
                        {
                            Id = (short)4,
                            Nome = "Cancelado"
                        });
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.FormaPagamento", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("FormaPagamentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Nome = "Dinheiro"
                        },
                        new
                        {
                            Id = (short)2,
                            Nome = "PIX"
                        },
                        new
                        {
                            Id = (short)3,
                            Nome = "Boleto"
                        });
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.HistoricoPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("DataPagamento")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int>("IdCobranca")
                        .HasColumnType("integer")
                        .HasColumnName("IdCobranca");

                    b.Property<short>("IdFormaPagamento")
                        .HasColumnType("smallint")
                        .HasColumnName("IdFormaPagamento");

                    b.Property<string>("Observacao")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("Observacao");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorPago");

                    b.HasKey("Id");

                    b.HasIndex("IdCobranca");

                    b.HasIndex("IdFormaPagamento");

                    b.ToTable("HistoricoPagamentos", (string)null);
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.Socio", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("Numero");

                    b.HasKey("Id");

                    b.ToTable("Socios", (string)null);
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.CaixaPostal", b =>
                {
                    b.HasOne("SistemaCaixaPostalIA.Models.Cliente", "Cliente")
                        .WithMany("CaixasPostais")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCaixaPostalIA.Models.Socio", "Socio")
                        .WithMany("CaixasPostais")
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCaixaPostalIA.Models.CaixaStatus", "CaixaStatus")
                        .WithMany()
                        .HasForeignKey("IdStatusCaixa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaixaStatus");

                    b.Navigation("Cliente");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.Cliente", b =>
                {
                    b.HasOne("SistemaCaixaPostalIA.Models.ClienteStatus", "ClienteStatus")
                        .WithMany()
                        .HasForeignKey("IdClienteStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteStatus");
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.Cobranca", b =>
                {
                    b.HasOne("SistemaCaixaPostalIA.Models.CaixaPostal", "CaixaPostal")
                        .WithMany("Cobrancas")
                        .HasForeignKey("IdCaixaPostal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCaixaPostalIA.Models.CobrancaStatus", "CobrancaStatus")
                        .WithMany()
                        .HasForeignKey("IdStatusCobranca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaixaPostal");

                    b.Navigation("CobrancaStatus");
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.HistoricoPagamento", b =>
                {
                    b.HasOne("SistemaCaixaPostalIA.Models.Cobranca", "Cobranca")
                        .WithMany("HistoricoPagamentos")
                        .HasForeignKey("IdCobranca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCaixaPostalIA.Models.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("IdFormaPagamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cobranca");

                    b.Navigation("FormaPagamento");
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.CaixaPostal", b =>
                {
                    b.Navigation("Cobrancas");
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.Cliente", b =>
                {
                    b.Navigation("CaixasPostais");
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.Cobranca", b =>
                {
                    b.Navigation("HistoricoPagamentos");
                });

            modelBuilder.Entity("SistemaCaixaPostalIA.Models.Socio", b =>
                {
                    b.Navigation("CaixasPostais");
                });
#pragma warning restore 612, 618
        }
    }
}
